services:
  centos7:
    image: centos:7
    container_name: centos7
    stdin_open: true
    tty: true
  ubuntu:
    image: ubuntu:latest
    build: ./
    container_name: ubuntu
    stdin_open: true
    tty: true