---
- name: restart clickhouse service
  become: true
  become_method: sudo
  become_user: root
  ansible.builtin.systemd:
    name: clickhouse-server
    state: restarted
    daemon_reload: true